Introduce GitHub Actions PR Check job, fixes JBIDE-27703
jbosstools/jbosstools-jst pull request #602
Opened 2021-03-30 21:14 UTC by odockal

2021-04-07 11:10 UTC, odockal commented
@sbouchet review please.

2021-04-20 13:21 UTC, sbouchet commented on .github/workflows/build_test.yml
> +        run: mvn clean verify -U -fae --settings build-ci/maven-settings.xml -DskipITests=true -Dmaven.test.error.ignore=true -Dmaven.test.failure.ignore=true --quiet
please add --no-transfer-progress

2021-04-28 11:50 UTC, odockal commented
@sbouchet review please.

2021-04-28 14:47 UTC, sbouchet requested changes

2021-04-28 14:47 UTC, sbouchet commented on .github/workflows/build_test.yml
> +        ref: ${{ github.event.pull_request.head.sha }}
please add fetch-depth: 0 to avoid baseline errors

2021-04-28 14:47 UTC, sbouchet commented on .github/workflows/build_test.yml
> +          -Dmaven.test.failure.ignore=true --quiet --no-transfer-progress
remove --quiet to better read logs.

2021-04-29 15:22 UTC, sbouchet approved these changes
LGTM

2021-04-30 12:46 UTC, merged